In [1]:
import epr_amplitude as e
import pandas as pd
import numpy as np

In [2]:
data001_1 = pd.read_csv('EPR_20161116_170644_001.csv')
data001_2 = pd.read_csv('EPR_20161116_170105_001.csv')
data001_3 = pd.read_csv('EPR_20161116_170151_001.csv')


In [22]:
epr1  = e.EPR(e.SW_clean(data001_1))

In [21]:
reload(e)

<module 'epr_amplitude' from 'epr_amplitude.py'>

In [23]:
epr1.s_filter()

array([ 1991.87066307,  2004.98067088,  1981.94060733,  1973.04334755,
        1980.59156296,  1992.80781322,  2000.25498815,  2000.85012937,
        1998.38309814,  1998.33577286,  2004.56706988,  2013.6573243 ,
        2019.06872332,  2011.06359476,  1989.19825396,  1951.33598893,
        1902.14499863,  1841.34028732,  1786.27310237,  1734.79884828,
        1696.3240827 ,  1670.45846596,  1672.92327728,  1701.62951188,
        1747.71486211,  1801.70670044,  1844.48590359,  1867.92030932,
        1878.86117396,  1876.99939804,  1875.02758936,  1872.40787383,
        1870.02798869,  1862.56529743,  1850.99908169,  1838.20572681,
        1828.60706241,  1821.15742922,  1813.80689752,  1804.23523579,
        1792.08509685,  1780.51040789,  1775.13047164,  1777.84285169,
        1772.29152773])

In [24]:
epr1.signal

array([ 1991.83333333,  2004.25      ,  1986.75      ,  1963.75      ,
        1983.5       ,  2002.25      ,  1994.25      ,  1999.5       ,
        1985.5       ,  2020.        ,  1999.5       ,  2011.        ,
        2006.75      ,  2026.        ,  1991.25      ,  1948.5       ,
        1895.25      ,  1844.75      ,  1782.25      ,  1748.75      ,
        1685.75      ,  1670.2       ,  1675.        ,  1703.25      ,
        1743.75      ,  1801.75      ,  1844.5       ,  1876.5       ,
        1871.75      ,  1878.75      ,  1872.25      ,  1866.75      ,
        1883.5       ,  1857.        ,  1851.25      ,  1837.25      ,
        1825.        ,  1828.25      ,  1809.        ,  1807.        ,
        1790.25      ,  1780.        ,  1777.        ,  1776.75      ,
        1772.5       ])

In [25]:
epr1.amplitude

355.79999999999995

In [26]:
epr1_f = e.EPR(epr1.s_filter())

In [27]:
epr1_f.amplitude

348.61025736187389

In [30]:
epr2  = e.EPR(e.SW_clean(data001_2))
print epr2.amplitude
epr2_f = e.EPR(epr2.s_filter())
epr2_f.amplitude

348.75


342.17536034159025

In [31]:
epr3  = e.EPR(e.SW_clean(data001_3))
print epr3.amplitude
epr3_f = e.EPR(epr3.s_filter())
epr3_f.amplitude

357.5


344.79144370509584

In [43]:
d = pd.DataFrame()

In [39]:
d['1'] = epr1_f.signal
d['2'] = epr2_f.signal
d['3'] = epr3_f.signal
d['Vpp Average'] = (epr1_f.amplitude + epr2_f.amplitude + epr3_f.amplitude)/3


In [40]:
d.to_csv('001_filtered.csv', index = False)

In [37]:
epr1_f.signal

array([ 1991.87066307,  2004.98067088,  1981.94060733,  1973.04334755,
        1980.59156296,  1992.80781322,  2000.25498815,  2000.85012937,
        1998.38309814,  1998.33577286,  2004.56706988,  2013.6573243 ,
        2019.06872332,  2011.06359476,  1989.19825396,  1951.33598893,
        1902.14499863,  1841.34028732,  1786.27310237,  1734.79884828,
        1696.3240827 ,  1670.45846596,  1672.92327728,  1701.62951188,
        1747.71486211,  1801.70670044,  1844.48590359,  1867.92030932,
        1878.86117396,  1876.99939804,  1875.02758936,  1872.40787383,
        1870.02798869,  1862.56529743,  1850.99908169,  1838.20572681,
        1828.60706241,  1821.15742922,  1813.80689752,  1804.23523579,
        1792.08509685,  1780.51040789,  1775.13047164,  1777.84285169,
        1772.29152773])

In [41]:
data002_1 = pd.read_csv('EPR_20161116_181152_002.csv')
data002_2 = pd.read_csv('EPR_20161116_181252_002.csv')
data002_3 = pd.read_csv('EPR_20161116_181422_002.csv')

In [42]:
epr1  = e.EPR(e.SW_clean(data002_1))
epr1_f = e.EPR(epr1.s_filter())
epr2  = e.EPR(e.SW_clean(data002_2))
epr2_f = e.EPR(epr2.s_filter())
epr3  = e.EPR(e.SW_clean(data002_3))
epr3_f = e.EPR(epr3.s_filter())

In [5]:
d = pd.DataFrame()
d['1'] = epr1_f.signal
d['2'] = epr2_f.signal
d['3'] = epr3_f.signal
d['Vpp Average'] = (epr1_f.amplitude + epr2_f.amplitude + epr3_f.amplitude)/3


In [6]:
d.to_csv('001_filtered_2.csv', index = False)

In [18]:
data001_1 = pd.read_csv('EPR_20161117_101134_001.csv')
data001_2 = pd.read_csv('EPR_20161117_095628_001.csv')
data001_3 = pd.read_csv('EPR_20161117_095513_001.csv')
data001_4 = pd.read_csv('EPR_20161117_104500_001.csv')

In [19]:
epr1  = e.EPR(e.SW_clean(data001_1))
epr1_f = e.EPR(epr1.s_filter())
epr2  = e.EPR(e.SW_clean(data001_2))
epr2_f = e.EPR(epr2.s_filter())
epr3  = e.EPR(e.SW_clean(data001_3))
epr3_f = e.EPR(epr3.s_filter())
epr4  = e.EPR(e.SW_clean(data001_4))
epr4_f = e.EPR(epr4.s_filter())

In [7]:
data002_1 = pd.read_csv('EPR_20161117_102545_002.csv')
data002_2 = pd.read_csv('EPR_20161117_102629_002.csv')
data002_3 = pd.read_csv('EPR_20161117_102813_002.csv')
data002_4 = pd.read_csv('EPR_20161117_102858_002.csv')

In [12]:
epr1  = e.EPR(e.SW_clean(data002_1))
epr1_f = e.EPR(epr1.s_filter())
epr2  = e.EPR(e.SW_clean(data002_2))
epr2_f = e.EPR(epr2.s_filter())
epr3  = e.EPR(e.SW_clean(data002_3))
epr3_f = e.EPR(epr3.s_filter())
epr4  = e.EPR(e.SW_clean(data002_4))
epr4_f = e.EPR(epr4.s_filter())

In [14]:
d = pd.DataFrame()
d['2'] = epr2_f.removeDC()
d['3'] = epr3_f.removeDC()
d['4'] = epr4_f.removeDC()
d['Vpp Average'] = (epr2_f.amplitude + epr3_f.amplitude + epr4_f.amplitude)/3

d.to_csv('002_filtered_2.csv', index = False)

In [11]:
reload(e)

<module 'epr_amplitude' from 'epr_amplitude.py'>

In [20]:
d = pd.DataFrame()
d['one'] = epr1_f.removeDC()
d['two'] = epr2_f.removeDC()
d['three'] = epr3_f.removeDC()
d['four'] = epr4_f.removeDC()
d['Vpp Average'] = (epr1_f.amplitude + epr2_f.amplitude + epr3_f.amplitude+epr4_f.amplitude)/4

d.to_csv('001_filtered_2.csv', index = False)

In [3]:
import glob
data = []
path = "/Users/manuelgodoy/Downloads/*006.csv"
df = pd.DataFrame()
for filename in glob.glob(path):
    d = pd.read_csv(filename)
    d_clean = e.EPR(e.SW_clean(d))
    d_filtered = e.EPR(d_clean.s_filter())
    data.append(d_filtered)
    df[filename] = d_filtered.removeDC()
    
average = []
for i in data:
    average.append(i.amplitude)
    
df['Vpp Average'] = sum(average)/float(len(average))
    
    


/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/scipy/linalg/basic.py:884: RuntimeWarning: internal gelsd driver lwork query error, required iwork dimension not returned. This is likely the result of LAPACK bug 0038, fixed in LAPACK 3.2.2 (released July 21, 2010). Falling back to 'gelss' driver.
  warnings.warn(mesg, RuntimeWarning)


ValueError: Length of values does not match length of index

In [31]:
df.to_csv('004_filtered.csv', index = False)

In [14]:
d = pd.read_csv('/Users/manuelgodoy/Downloads/EPR_20161117_110538_006.csv')
d2 = pd.read_csv('/Users/manuelgodoy/Downloads/EPR_20161117_110441_006.csv')
d_clean = e.EPR(e.SW_clean(d))
d_clean2 = e.EPR(e.SW_clean(d2))
d_filtered = e.EPR(d_clean.s_filter())
d_filtered2 = e.EPR(d_clean2.s_filter())
df = pd.DataFrame()

ValueError: Length of values does not match length of index

In [6]:
d_clean = e.EPR(e.SW_clean(d))


In [8]:
d_filtered = e.EPR(d_clean.s_filter())

In [10]:
d_filtered.amplitude

230.14885615546922

In [12]:
df = pd.DataFrame()
df['on'] = d_filtered.removeDC()

In [13]:
df.to_csv('006.csv')

In [15]:
print len(d_filtered.removeDC())
print len(d_filtered2.removeDC())

67
45


In [17]:
df2 = pd.DataFrame()
df2['on'] = d_filtered2.removeDC()
df2.to_csv('006_2.csv')


In [1]:
import pandas as pd
import numpy as np
data10 = pd.read_csv('/Users/manuelgodoy/Dropbox/Projects/Cenovus Weyburn Trials/Data/EPR_20161120_113225_192e.csv')


In [2]:
import epr_amplitude as e

In [3]:
df = e.SW_width(data)

In [30]:
reload(e)

<module 'epr_amplitude' from 'epr_amplitude.pyc'>

In [20]:
E = e.EPR(df['EPR'])

In [21]:
E.magnetic_field = df['Field']

In [16]:
max_ind = np.where(E.signal==E.maxima)[0][0]
min_ind = np.where(E.signal==E.minima)[0][0]

In [17]:
max_ind, min_ind

(14, 24)

In [22]:
E.width()

0     0.699921
1     0.700378
2     0.700836
3     0.701294
4     0.701752
5     0.702209
6     0.702667
7     0.703125
8     0.703583
9     0.704041
10    0.704498
11    0.704956
12    0.705414
13    0.705872
14    0.706329
15    0.706787
16    0.707245
17    0.707703
18    0.708160
19    0.708618
20    0.709076
21    0.709534
22    0.709991
23    0.710449
24    0.710907
25    0.711365
26    0.711823
27    0.712280
28    0.712738
29    0.713196
30    0.713654
31    0.714111
32    0.714569
33    0.715027
34    0.715485
35    0.715942
36    0.716400
37    0.716858
38    0.717316
39    0.717773
40    0.718231
41    0.718689
42    0.719147
43    0.719604
44    0.719910
Name: Field, dtype: float64
14
24


0.004577999999999971

In [15]:
np.abs(-1)

1

In [31]:
data00 = pd.read_csv('/Users/manuelgodoy/Dropbox/Projects/Cenovus Weyburn Trials/Data/EPR_20161120_115308_191e.csv')
data10 = pd.read_csv('/Users/manuelgodoy/Dropbox/Projects/Cenovus Weyburn Trials/Data/EPR_20161120_113225_192e.csv')
data30 = pd.read_csv('/Users/manuelgodoy/Dropbox/Projects/Cenovus Weyburn Trials/Data/EPR_20161120_113609_193e.csv')
data60 = pd.read_csv('/Users/manuelgodoy/Dropbox/Projects/Cenovus Weyburn Trials/Data/EPR_20161120_114025_194e.csv')

In [36]:
df00 = e.SW_width(data00)
df10 = e.SW_width(data10)
df30 = e.SW_width(data30)
df60 = e.SW_width(data60)

In [37]:
E00 = e.EPR(df00['EPR'])
E00.magnetic_field = df00['Field']
E10 = e.EPR(df10['EPR'])
E10.magnetic_field = df10['Field']
E30 = e.EPR(df30['EPR'])
E30.magnetic_field = df30['Field']
E60 = e.EPR(df60['EPR'])
E60.magnetic_field = df60['Field']

In [38]:
print E00.width()
print E10.width()
print E30.width()
print E60.width()

0.004119
0.004425
0.003967
0.004425


In [35]:
data00 = pd.read_csv('/Users/manuelgodoy/Dropbox/Projects/Cenovus Weyburn Trials/Data/EPR_20161120_115124_191e.csv')
data10 = pd.read_csv('/Users/manuelgodoy/Dropbox/Projects/Cenovus Weyburn Trials/Data/EPR_20161120_113040_192e.csv')
data30 = pd.read_csv('/Users/manuelgodoy/Dropbox/Projects/Cenovus Weyburn Trials/Data/EPR_20161120_113437_193e.csv')
data60 = pd.read_csv('/Users/manuelgodoy/Dropbox/Projects/Cenovus Weyburn Trials/Data/EPR_20161120_113829_194e.csv')

In [29]:
max_ind

19

In [30]:
min_ind

28

In [31]:
np.where(E30.signal == E30.maxima)[0][0]
np.where(E30.signal == E30.minima)[0][0]

28

In [32]:
np.where(E30.signal == E30.maxima)[0][0]

20

In [33]:
np.where(E60.signal == E60.minima)[0][0]

28

In [34]:
np.where(E60.signal == E60.maxima)[0][0]

21

In [2]:
data00 = pd.read_csv('/Users/manuelgodoy/Dropbox/Projects/Cenovus Weyburn Trials/Data/EPR_20161122_114638_035h.csv')
data10 = pd.read_csv('/Users/manuelgodoy/Dropbox/Projects/Cenovus Weyburn Trials/Data/EPR_20161122_114157_074h.csv')
df00 = e.SW_width(data00)
df10 = e.SW_width(data10)
E00 = e.EPR(df00['EPR'])
E00.magnetic_field = df00['Field']
E10 = e.EPR(df10['EPR'])
E10.magnetic_field = df10['Field']
print E00.width()
print E10.width()

0.00412
0.00412


In [4]:
data00 = pd.read_csv('/Users/manuelgodoy/Dropbox/Projects/Cenovus Weyburn Trials/Data/EPR_20161122_113752_035h.csv')
data10 = pd.read_csv('/Users/manuelgodoy/Dropbox/Projects/Cenovus Weyburn Trials/Data/EPR_20161122_115035_074h.csv')
df00 = e.SW_width(data00)
df10 = e.SW_width(data10)
E00 = e.EPR(df00['EPR'])
E00.magnetic_field = df00['Field']
E10 = e.EPR(df10['EPR'])
E10.magnetic_field = df10['Field']
print E00.width()
print E10.width()

0.00351
0.003968


In [5]:
data00 = pd.read_csv('/Users/manuelgodoy/Dropbox/Projects/Cenovus Weyburn Trials/Data/EPR_20161122_113414_035h.csv')
data10 = pd.read_csv('/Users/manuelgodoy/Dropbox/Projects/Cenovus Weyburn Trials/Data/EPR_20161122_114259_074h.csv')
df00 = e.SW_width(data00)
df10 = e.SW_width(data10)
E00 = e.EPR(df00['EPR'])
E00.magnetic_field = df00['Field']
E10 = e.EPR(df10['EPR'])
E10.magnetic_field = df10['Field']
print E00.width()
print E10.width()

0.004425
0.003356
