In [1]:
from epr_amplitude import EPR


In [1]:
import datetime
datetime.datetime.now().strftime("%B %d %Y %H:%M:%S")

'November 02 2016 15:44:22'

In [2]:
import pandas as pd
import numpy as np

In [3]:
data = pd.read_csv('EPR_Magnet_Cen131_DiscreteBox_2LPF_October 31 2016 19:45:47.csv')

In [4]:
e = EPR(data['X'])

NameError: name 'EPR' is not defined

In [37]:
class EPR(object):
    """This is an object for the EPR signal, the EPR Signal must be a np array"""
    def __init__(self, signal):
        self.signal = np.array(signal)
        self.time = datetime.datetime.now().strftime("%B %d %Y %H:%M:%S")
        # self.maxima = None
        # self.minima = None
        # self.amplitude = None

    def set_maxima(self):
        # for local maxima
        indices_max = argrelextrema(self.signal, np.greater)
        self.maxima = self.signal[indices_max[0]].max()
        return self.maxima

    def set_minima(self):
        # for local minima
        indices_min = argrelextrema(self.signal, np.less)
        self.minima = self.signal[indices_min[0]].min()
        return self.minima

    def set_amplitude(self):
        self.amplitude = self.maxima - self.minima
        return self.amplitude

    def peaks(self):
        """signal must be a np array"""

        if not hasattr(self, 'maxima'):
            self.set_maxima()
        if not hasattr(self,'minima'):
            self.set_minima()

        return self.maxima, self.minima

    def mid_point_index(self):
        # maxima, minima = peaks(signal)
        if self.maxima and self.minima:
            max_ind = np.where(signal == self.maxima)[0][0]
            min_ind = np.where(signal == self.minima)[0][0]
            return abs((max_ind-min_ind)/2)
        return None

In [38]:
e = EPR(data['X'])

In [39]:
e.peaks()

(0.0022767500000000001, 0.00190453)

In [40]:
e.set_amplitude()

0.00037222000000000015

In [27]:
f = EPR(np.array(data['X']))

In [29]:
f.set_maxima()

0.0022767500000000001

In [30]:
a = np.array(data['X'])

In [32]:
np.array(a)

array([ 0.0021844 ,  0.00217917,  0.00217876,  0.00217826,  0.00217574,
        0.00217353,  0.00217131,  0.00217232,  0.00217826,  0.00218894,
        0.00220263,  0.00222016,  0.00223577,  0.00225359,  0.00226779,
        0.00227675,  0.00227232,  0.00224352,  0.00218591,  0.00210676,
        0.00202951,  0.00195962,  0.00191551,  0.00190453,  0.00192155,
        0.00195589,  0.00199356,  0.00202437,  0.00204875,  0.00206416,
        0.00207483,  0.00208218,  0.00208591,  0.00208178,  0.00208037,
        0.00207423,  0.00206698,  0.00206295,  0.0020566 ,  0.00204925])

In [36]:
f.peaks()

AttributeError: 'EPR' object has no attribute 'minima'

In [5]:
e.peaks()

(0.0022767500000000001, 0.00190453)

In [7]:
e.set_amplitude()

0.00037222000000000015

In [8]:
e.amplitude

0.00037222000000000015

In [12]:
e.signal[-5:].std()

8.5673599200687103e-06

In [13]:
e.signal[:5].std()

2.8308274408731136e-06

In [14]:
e.mid_point_index()

NameError: global name 'signal' is not defined

In [38]:
from epr_amplitude import EPR

In [5]:
e = EPR(data['X'])

In [6]:
e.mid_point_index()

In [7]:
e.set_maxima()
e.set_minima()

0.00190453

In [8]:
e.mid_point_index()

4

In [9]:
e.signal

array([ 0.0021844 ,  0.00217917,  0.00217876,  0.00217826,  0.00217574,
        0.00217353,  0.00217131,  0.00217232,  0.00217826,  0.00218894,
        0.00220263,  0.00222016,  0.00223577,  0.00225359,  0.00226779,
        0.00227675,  0.00227232,  0.00224352,  0.00218591,  0.00210676,
        0.00202951,  0.00195962,  0.00191551,  0.00190453,  0.00192155,
        0.00195589,  0.00199356,  0.00202437,  0.00204875,  0.00206416,
        0.00207483,  0.00208218,  0.00208591,  0.00208178,  0.00208037,
        0.00207423,  0.00206698,  0.00206295,  0.0020566 ,  0.00204925])

In [11]:
e.maxima, e.minima

(0.0022767500000000001, 0.00190453)

In [13]:
 np.where(e.signal == e.maxima)[0][0]

15

In [14]:
 np.where(e.signal == e.minima)[0][0]

23

In [16]:
(15+23)/2

19

In [17]:
(15+22)/2

18

In [20]:
data['Voltage Magnet'][18]

0.71399999999999997

In [21]:
data['Voltage Magnet']

0     0.7050
1     0.7055
2     0.7060
3     0.7065
4     0.7070
5     0.7075
6     0.7080
7     0.7085
8     0.7090
9     0.7095
10    0.7100
11    0.7105
12    0.7110
13    0.7115
14    0.7120
15    0.7125
16    0.7130
17    0.7135
18    0.7140
19    0.7145
20    0.7150
21    0.7155
22    0.7160
23    0.7165
24    0.7170
25    0.7175
26    0.7180
27    0.7185
28    0.7190
29    0.7195
30    0.7200
31    0.7205
32    0.7210
33    0.7215
34    0.7220
35    0.7225
36    0.7230
37    0.7235
38    0.7240
39    0.7245
Name: Voltage Magnet, dtype: float64

In [22]:
from scipy.signal import argrelextrema
import datetime
import numpy as np

class EPR(object):
    """This is an object for the EPR signal, the EPR Signal must be a list """
    def __init__(self, signal):
        self.signal = np.array(signal)
        self.time = datetime.datetime.now().strftime("%B %d %Y %H:%M:%S")
        # self.maxima = None
        # self.minima = None
        # self.amplitude = None

    def set_maxima(self):
        # for local maxima
        indices_max = argrelextrema(self.signal, np.greater)
        self.maxima = self.signal[indices_max[0]].max()
        return self.maxima

    def set_minima(self):
        # for local minima
        indices_min = argrelextrema(self.signal, np.less)
        self.minima = self.signal[indices_min[0]].min()
        return self.minima

    def set_voltage_vector(self, voltage):
        self.voltage = np.array(voltage)
        return

    def set_bfield_vector(self, bfield):
        self.bfield = np.array(bfield)
        return

    def amplitude(self):
        self.amplitude = self.maxima - self.minima
        return self.amplitude

    def peaks(self):
        """signal must be a np array"""

        if not hasattr(self, 'maxima'):
            self.set_maxima()
        if not hasattr(self,'minima'):
            self.set_minima()

        return self.maxima, self.minima

    def mid_point_index(self):
        # maxima, minima = peaks(signal)
        if not hasattr(self, 'maxima') and not hasattr(self,'minima'):
            self.set_maxima()
            self.set_minima()
        max_ind = np.where(self.signal == self.maxima)[0][0]
        min_ind = np.where(self.signal == self.minima)[0][0]
        return (max_ind+min_ind)/2
        # return None

    def noise(self):
        """This functions takes 5 measurements away from the EPR signal and
        measures their std dev. A phase difference at the mixer may skey this value
        """
        return self.signal[:5].std()


In [23]:
EPR.efield= [1,2,3,4,5]

In [24]:
EPR.efield

[1, 2, 3, 4, 5]

In [5]:
from epr_signal import EPR

In [6]:
e.maxima

0.0022767500000000001

In [7]:
e.amplitude

0.00037222000000000015

In [6]:
e = EPR(data['X'])

In [9]:
e.noise(from_beginning=False)

0.00010594646824405126

In [10]:
e.noise()

2.8308274408731136e-06

In [14]:
e.signal[-5:].std()

8.5673599200687103e-06

In [16]:
e.signal[-5:]

array([ 0.00207423,  0.00206698,  0.00206295,  0.0020566 ,  0.00204925])

In [18]:
e.signal[:5]

array([ 0.0021844 ,  0.00217917,  0.00217876,  0.00217826,  0.00217574])

In [23]:
import math
def to_db(self):
    return 10*math.log10(self*self/0.050)

In [24]:
r = EPR(data['R'])

In [25]:
to_db(r.signal)

TypeError: only length-1 arrays can be converted to Python scalars

In [30]:
10*np.log10(r.signal*r.signal/0.050)

array([-40.02075988, -40.04040655, -40.0415774 , -40.04352916,
       -40.05259108, -40.06440139, -40.07387687, -40.06835478,
       -40.04352916, -40.00197344, -39.94852069, -39.8799417 ,
       -39.82072327, -39.7504995 , -39.69444141, -39.65937317,
       -39.67481269, -39.78859167, -40.01682809, -40.34230454,
       -40.67537188, -40.98879598, -41.18967599, -41.24007029,
       -41.16281152, -41.00635552, -40.83798239, -40.70291592,
       -40.59542296, -40.52696908, -40.47930468, -40.44877745,
       -40.43353356, -40.4491865 , -40.45782199, -40.48673759,
       -40.51867695, -40.53861619, -40.5665585 , -40.59417503])

In [39]:
10*np.log10(np.array(data['R'])*np.array(data['R'])/0.050)

array([-40.02075988, -40.04040655, -40.0415774 , -40.04352916,
       -40.05259108, -40.06440139, -40.07387687, -40.06835478,
       -40.04352916, -40.00197344, -39.94852069, -39.8799417 ,
       -39.82072327, -39.7504995 , -39.69444141, -39.65937317,
       -39.67481269, -39.78859167, -40.01682809, -40.34230454,
       -40.67537188, -40.98879598, -41.18967599, -41.24007029,
       -41.16281152, -41.00635552, -40.83798239, -40.70291592,
       -40.59542296, -40.52696908, -40.47930468, -40.44877745,
       -40.43353356, -40.4491865 , -40.45782199, -40.48673759,
       -40.51867695, -40.53861619, -40.5665585 , -40.59417503])

In [40]:
data['Rdb']-10*np.log10(np.array(data['R'])*np.array(data['R'])/0.050)

0    -0.020740
1    -0.021193
2    -0.020023
3    -0.024871
4    -0.022509
5    -0.024099
6    -0.021323
7    -0.020145
8    -0.024871
9    -0.019427
10   -0.019179
11   -0.020558
12   -0.019377
13   -0.022400
14   -0.024759
15   -0.019627
16   -0.024287
17   -0.024608
18   -0.024672
19   -0.021495
20   -0.024128
21   -0.019504
22   -0.020024
23   -0.023330
24   -0.020088
25   -0.022044
26   -0.022618
27   -0.023384
28   -0.023477
29   -0.024831
30   -0.018695
31   -0.022423
32   -0.024266
33   -0.022013
34   -0.020078
35   -0.018062
36   -0.019623
37   -0.019884
38   -0.018742
39   -0.024725
Name: Rdb, dtype: float64

In [41]:
data['test'] = 4

In [42]:
data['test']

0     4
1     4
2     4
3     4
4     4
5     4
6     4
7     4
8     4
9     4
10    4
11    4
12    4
13    4
14    4
15    4
16    4
17    4
18    4
19    4
20    4
21    4
22    4
23    4
24    4
25    4
26    4
27    4
28    4
29    4
30    4
31    4
32    4
33    4
34    4
35    4
36    4
37    4
38    4
39    4
Name: test, dtype: int64

In [89]:
datas = []
datas.append(data['R pp'][0])
df = pd.DataFrame()
df['R 1'] = data['R']

df['Error'] = np.append([1],np.empty(len(df)-1) * np.nan)

In [91]:
df.to_csv('testing.csv', index = False)

In [96]:
datas = []
datas.append(data['R pp'][0])
df = pd.DataFrame()
df['R 1'] = data['R']

df['Error'] = pd.Series(1)

In [97]:
df

R 1  Error
0   0.002231    1.0
1   0.002226    NaN
2   0.002225    NaN
3   0.002225    NaN
4   0.002223    NaN
5   0.002220    NaN
6   0.002217    NaN
7   0.002219    NaN
8   0.002225    NaN
9   0.002236    NaN
10  0.002249    NaN
11  0.002267    NaN
12  0.002283    NaN
13  0.002301    NaN
14  0.002316    NaN
15  0.002325    NaN
16  0.002321    NaN
17  0.002291    NaN
18  0.002232    NaN
19  0.002150    NaN
20  0.002069    NaN
21  0.001995    NaN
22  0.001950    NaN
23  0.001939    NaN
24  0.001956    NaN
25  0.001991    NaN
26  0.002030    NaN
27  0.002062    NaN
28  0.002088    NaN
29  0.002104    NaN
30  0.002116    NaN
31  0.002123    NaN
32  0.002127    NaN
33  0.002123    NaN
34  0.002121    NaN
35  0.002114    NaN
36  0.002106    NaN
37  0.002102    NaN
38  0.002095    NaN
39  0.002088    NaN

In [79]:
type(df['R 1'][0])

numpy.float64

In [71]:
type(np.float(1))

float

In [86]:
np.append(np.array([1]),np.array([2,3]))

array([1, 2, 3])

In [85]:
np.array([2,3])

array([2, 3])